apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitlog
spec:
  workspaces:
    - name: source
      workspace: shared-data
  results:
    - name: modified
      description: files modified
    - name: deleted
      description: files deleted
    - name: created
      description: files created
  steps:
    - name: interrogate git log
      image: enterpriseautomation/tekton.gitlog    
      script: |
        #!/usr/bin/env bash
        cd $(workspaces.source.path)
        /app/main | tee $(results.modified.path)